# DAO QA environment
image:
  repository: 886436934082.dkr.ecr.us-east-1.amazonaws.com/rscoll-dev-dao-qa
  tag: 14231be7f0a0b4588e946909049402a285ffec19

namespace: dao-frontend-qa

ingress:
  enabled: false

externalSecrets:
  parameterPaths:
    theGraphApiKey: /rscoll-dev/dao-qa/the-graph-api-key
    dbConnectionString: /rscoll-dev/dao-qa/database-uri
    daoGraphApiKey: /rscoll-dev/dao-qa/dao-graph-api-key
