# Release Candidate Mainnet environment
image:
  repository: 886436934082.dkr.ecr.us-east-1.amazonaws.com/rscoll-dev-dao-rc-mainnet
  tag: 639c6872f43776d4befd5ddd8fd39825e99d6b39

namespace: dao-frontend-rc-mainnet

ingress:
  enabled: false

externalSecrets:
  parameterPaths:
    theGraphApiKey: /rscoll-dev/rc-mainnet/the-graph-api-key
    dbConnectionString: /rscoll-dev/dao-rc-mainnet/database-uri
    daoGraphApiKey: /rscoll-dev/rc-mainnet/dao-graph-api-key
