# Release Candidate Testnet environment
image:
  repository: 886436934082.dkr.ecr.us-east-1.amazonaws.com/rscoll-dev-dao-staging
  tag: 639c6872f43776d4befd5ddd8fd39825e99d6b39

namespace: dao-frontend-rc-testnet

ingress:
  enabled: false

externalSecrets:
  parameterPaths:
    theGraphApiKey: /rscoll-dev/rc-testnet/the-graph-api-key
    dbConnectionString: /rscoll-dev/dao-staging/database-uri
    daoGraphApiKey: /rscoll-dev/rc-testnet/dao-graph-api-key
