# CR QA environment
image:
  repository: 886436934082.dkr.ecr.us-east-1.amazonaws.com/rscoll-dev-bim-qa
  tag: 615a41a35d6e1d01b365a5fe8909a448469f3edc

namespace: dao-frontend-cr-qa

ingress:
  enabled: true
  className: alb
  certificateArn: "arn:aws:acm:us-east-1:886436934082:certificate/aa176147-46df-47b0-9856-84ee57b4fa5d"
  hosts:
    - host: qa-eks.cr.rootstockcollective.xyz
      paths:
        - path: /
          pathType: Prefix
  annotations: {}

externalSecrets:
  parameterPaths:
    theGraphApiKey: /rscoll-dev/cr-qa/the-graph-api-key
    dbConnectionString: /rscoll-state-sync/cr-qa/database-uri
    daoGraphApiKey: /rscoll-dev/cr-qa/dao-graph-api-key
