name: Vanguard Boost schedule

# Declare default permissions as read only.
permissions: read-all

env:
  BOOST: '30'
  NFT_CONTRACT: '0x1EEA464C8632A71A2E9B364725da6e09aaed2Ddc'
  ENVIRONMENT: 'mainnet'

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at noon UTC

jobs:
  boost:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: '22'

      - name: Install dependencies
        run:  npm install --production

      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global push.autoSetupRemote true

      - name: Set BOOST_DATA_BRANCH
        run: echo "BOOST_DATA_BRANCH=boost_data/${{ env.ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Boost backers' rewards
        run: |
          npx tsx .github/scripts/nft_boost/activateBoost.ts \
              --boost=${{ env.BOOST }} \
              --nft=${{ env.NFT_CONTRACT }} \
              --env=${{ env.ENVIRONMENT }}
          git add .
          git diff --cached > ./boost.diff
          echo "Changes:"
          cat ./boost.diff
          echo "End of changes"
          git fetch origin
          git checkout $BOOST_DATA_BRANCH --force || git checkout -b $BOOST_DATA_BRANCH
          git apply boost.diff --3way --theirs
          rm -f boost.diff
          git add .
          git commit -m "Add files generated by boost script" || echo "No changes to commit"
          git push --force
